[package]
name = "vidhan-site"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "build/main.rs"
publish.workspace = true

[workspace]
members = [".", "assets"]

[workspace.package]
authors = ["Vidhan Bhatt <me@vidhan.io>"]
version = "0.0.0"
edition = "2024"
license = "AGPL-3.0-only"
publish = false

[workspace.dependencies]
hypertext.git = "https://github.com/vidhanio/hypertext"
thiserror = "2"
vidhan-site-assets = { path = "assets" }

[dependencies]
aho-corasick = "1"
axum = { version = "0.8", features = ["macros", "tracing"] }
axum-extra = { version = "0.12", features = ["typed-header"] }
color-eyre = "0.6"
dotenvy = "0.15"
envy = "0.4"
futures-util = { version = "0.3", default-features = false }
hypertext = { workspace = true, features = ["axum"] }
mime = "0.3"
serde = { version = "1", features = ["derive"] }
thiserror.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.7", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
vidhan-site-assets = { workspace = true, optional = true }

[features]
default = []
reload = ["dep:vidhan-site-assets"]

[build-dependencies]
vidhan-site-assets.workspace = true
prettyplease = "0.3"
quote = "1"
syn = { version = "3", default-features = false, features = ["parsing"] }

[lints]
[lints.clippy]
nursery = "warn"
pedantic = "warn"

[lints.rust]
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
unsafe_code = "forbid"
