[package]
name = "vidhan-site"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "build/main.rs"
publish.workspace = true

[workspace]
members = ["."]

[workspace.package]
authors = ["Vidhan Bhatt <me@vidhan.io>"]
version = "0.0.0"
edition = "2024"
license = "AGPL-3.0-only"
publish = false

[workspace.dependencies]
hypertext.git = "https://github.com/vidhanio/hypertext"
hypertext.branch = "rewrite"
thiserror = "2"

[dependencies]
aho-corasick = "1"
axum = { version = "0.8", features = ["macros", "tracing"] }
axum-extra = { version = "0.12", features = ["typed-header"] }
color-eyre = "0.6"
dotenvy = "0.15"
envy = "0.4"
futures-util = { version = "0.3", default-features = false }
hypertext = { workspace = true, features = ["axum"] }
mime = "0.3"
moka = { version = "0.12.16", features = ["future"] }
rspotify = { version = "0.16", default-features = false, features = [
  "client-reqwest",
  "reqwest-rustls-tls",
] }
serde = { version = "1", features = ["derive"] }
thiserror.workspace = true
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.7", features = ["trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }

[build-dependencies]
heck = "0.5"
html-escape = "0.2"
hypertext.workspace = true
ico = "0.5"
prettyplease = "0.3"
proc-macro2 = "1"
pulldown-cmark = "0.13"
quote = "1"
resvg = { version = "0.48", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
syn = { version = "3", default-features = false, features = ["parsing"] }
time = "0.3"
tree-sitter = "0.27"
tree-sitter-css = "0.25"
tree-sitter-highlight = "0.27"
tree-sitter-html = "0.23"
tree-sitter-java = "0.23"
tree-sitter-rust = "0.24"
typst = "0.15"
typst-kit = { version = "0.15", default-features = false, features = [
  "scan-fonts",
] }
typst-layout = "0.15"
typst-pdf = "0.15"
typst-render = "0.15"
ureq = "3"
which = "8"

[lints]
[lints.clippy]
nursery = "warn"
pedantic = "warn"

[lints.rust]
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
unsafe_code = "forbid"
