[package]
name = "vidhan-site-assets"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
heck = "0.5"
html-escape = "0.2"
hypertext.workspace = true
ico = "0.5"
prettyplease = "0.3"
pulldown-cmark = "0.13"
quote = "1"
resvg = { version = "0.48", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
syn = { version = "3", default-features = false, features = ["parsing"] }
time = "0.3"
tree-sitter = "0.27"
tree-sitter-css = "0.25"
tree-sitter-highlight = "0.27"
tree-sitter-html = "0.23"
tree-sitter-java = "0.23"
tree-sitter-rust = "0.24"
typst = "0.15"
typst-kit = { version = "0.15", default-features = false, features = [
  "scan-fonts",
] }
typst-layout = "0.15"
typst-pdf = "0.15"
typst-render = "0.15"
typst-svg = "0.15"

[lints]
[lints.clippy]
nursery = "warn"
pedantic = "warn"

[lints.rust]
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
unsafe_code = "forbid"
