import fs from "fs";
import matter from "gray-matter";
import { GetStaticPropsResult } from "next";
import Link from "next/link";
import path from "path";
import { postFilePaths, POSTS_PATH } from "../utils/mdx-utils";

interface Props {
  posts: {
    fileContent: string;
    fileFrontmatter: {
      [key: string]: any;
    };
    filePath: string;
  }[];
}

export default function Index({ posts }: Props) {
  return (
    <>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/posts/${post.filePath.replace(/\.mdx?$/, "")}`}
              href={`/posts/[slug]`}
            >
              <a>{post.fileFrontmatter.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </>
  );
}

export async function getStaticProps(): Promise<GetStaticPropsResult<Props>> {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
    const { content, data } = matter(source);

    return {
      content: content,
      frontmatter: data,
      path: filePath,
    };
  });

  return {
    props: {
      posts: posts,
    },
  };
}
