name: security audit

on:
  schedule:
    - cron: "0 0 * * *"

  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "**/deny.toml"

  pull_request:

jobs:
  cargo-deny:
    name: security audit

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: run cargo deny
        uses: EmbarkStudios/cargo-deny-action@v2
